# Generated by Django 5.2.8 on 2025-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncresult',
            name='added_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syncresult',
            name='updated_count',
            field=models.IntegerField(default=0),
        ),
    ]
