# Generated by Django 5.2.8 on 2025-11-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_emailoutbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailoutbox',
            old_name='processed_at',
            new_name='last_attempt_at',
        ),
        migrations.RemoveField(
            model_name='emailoutbox',
            name='registration',
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='to_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
